# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""Repo-wide gate on IAM permission-mutation actions in CloudFormation templates.

Motivated by **AppSec finding b2b397a9** (High). The Security Invariant scan's
``iam-role-without-privilege-escalation`` check, scenario 1.1, found that
``AgentCoreGatewayManagerFunctionRole`` "can add permissions to itself":
``AgentCoreGatewayManagerFunction``'s inline policy granted ``iam:CreateRole``,
``iam:AttachRolePolicy`` and ``iam:PassRole`` on ``Resource: "*"``, so the role
could attach ``AdministratorAccess`` to itself and escalate out of every other
boundary in the stack. It was never needed — the function is a CloudFormation
custom resource that creates one AgentCore Gateway against a role
CloudFormation has already built for it (see ``src/lambda/
agentcore_gateway_manager/index.py``).

The fix removed those actions. Nothing stopped them coming back, and the SI scan
runs against a *deployed* account rather than a PR, so a reintroduction would
ship and only be caught on the next scan. This gate closes that gap at review
time.

Rule enforced: **no IAM policy statement in any template may grant an action
that mutates IAM permissions** — unless the template is in
``DEPLOYMENT_ROLE_TEMPLATES``, which lists, with justification, the few roles
that exist precisely in order to create the stack's roles.

``iam:PassRole`` is deliberately NOT in ``MUTATION_ACTIONS``. Passing a role is
not adding a permission, and a custom resource that hands an execution role to
a service legitimately needs it; the risk in ``PassRole`` is its *resource*
scope, which is what ``test_pass_role_is_scoped`` covers separately.

Two known seams, both shared with the sibling gate in
``test_lambda_log_groups.py``:

* **``Fn::If`` is expanded, but only in the 3-arity form.** A malformed
  ``Fn::If`` is invisible here; cfn-lint rejects it, so nothing ships.
* **``Fn::ForEach`` / ``Transform: AWS::LanguageExtensions`` is invisible.** A
  ``Fn::ForEach::X`` key under ``Resources`` maps to a list, so a policy
  generated by it is not scanned. The repo does not use it today (checked); if
  that changes, this gate must be taught about it rather than trusted.
"""

from __future__ import annotations

import fnmatch
import os
from pathlib import Path
from typing import Any, Iterator

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]

# Actions that let a principal grant permissions — to itself or to anything it
# can reach. This is the privilege-escalation set the SI check reasons about,
# not "every write action in the iam namespace": iam:TagRole and iam:DeleteRole
# are destructive but cannot widen a permission set, so they are out.
MUTATION_ACTIONS = frozenset(
    {
        "iam:*",
        # Inline policies.
        "iam:putrolepolicy",
        "iam:putuserpolicy",
        "iam:putgrouppolicy",
        # Managed policies.
        "iam:attachrolepolicy",
        "iam:attachuserpolicy",
        "iam:attachgrouppolicy",
        "iam:createpolicy",
        "iam:createpolicyversion",
        "iam:setdefaultpolicyversion",
        # New principals, and credentials on existing ones.
        "iam:createrole",
        "iam:createuser",
        "iam:createaccesskey",
        "iam:createloginprofile",
        "iam:updateloginprofile",
        "iam:createinstanceprofile",
        "iam:addusertogroup",
        # Trust policy: who may assume the role at all.
        "iam:updateassumerolepolicy",
        "iam:updaterole",
        # Permissions boundaries are the ceiling every other grant sits under.
        "iam:putrolepermissionsboundary",
        "iam:deleterolepermissionsboundary",
    }
)

# Templates whose whole purpose is to create the roles an IDP stack needs.
# These are assumed by CloudFormation or by a human deployer, never by stack
# runtime code, so "can create a role" is their function rather than a defect.
# They are also not deployed by the stack itself.
DEPLOYMENT_ROLE_TEMPLATES: dict[str, str] = {
    "iam-roles/cloudformation-management/IDP-Cloudformation-Service-Role.yaml": (
        "The CloudFormation service role. CloudFormation assumes it to create "
        "every IAM role in the stack, so it must be able to create and attach "
        "policies. Scoped and documented in iam-roles/cloudformation-management/"
        "README.md; no Lambda or runtime code can assume it."
    ),
    "scripts/sdlc/cfn/sdlc-iam-role.yml": (
        "SDLC bootstrap role for the CI/CD account, applied by hand outside the "
        "product stack. Not referenced by template.yaml or any pattern stack."
    ),
    "scripts/sdlc/cfn/codepipeline-s3.yml": (
        "CodePipeline bootstrap stack for the SDLC account, applied by hand. "
        "Not referenced by template.yaml or any pattern stack."
    ),
}

PRUNED_DIRS = frozenset(
    {".aws-sam", "node_modules", ".venv", "build", "dist", ".git", "__pycache__"}
)


class _CfnLoader(yaml.SafeLoader):
    """SafeLoader that tolerates CloudFormation short-form tags."""


def _tag_to_python(loader, tag_suffix, node):
    if isinstance(node, yaml.ScalarNode):
        return {f"Fn::{tag_suffix}": loader.construct_scalar(node)}
    if isinstance(node, yaml.SequenceNode):
        return {f"Fn::{tag_suffix}": loader.construct_sequence(node, deep=True)}
    return {f"Fn::{tag_suffix}": loader.construct_mapping(node, deep=True)}


_CfnLoader.add_multi_constructor("!", _tag_to_python)


def _load_text(text: str) -> Any:
    return yaml.load(text, Loader=_CfnLoader)


def _branches(node: Any) -> list[Any]:
    """Every value ``node`` can evaluate to, expanding ``Fn::If`` branches.

    A statement reached only through one ``Fn::If`` leg is still a statement
    that deploys, so each leg is checked independently.
    """
    if isinstance(node, dict) and "Fn::If" in node:
        value = node["Fn::If"]
        if isinstance(value, list) and len(value) == 3:
            return [b for branch in value[1:] for b in _branches(branch)]
    return [node]


def _statements(node: Any) -> Iterator[dict]:
    """Every policy statement anywhere in a template.

    Deliberately keyed on ``Statement`` rather than on resource type: the same
    shape appears in an ``AWS::IAM::Role``'s ``Policies``, in an
    ``AWS::IAM::ManagedPolicy``, in a SAM function's ``Policies`` list, in a
    bucket or KMS key resource policy, and in ``AssumeRolePolicyDocument``. A
    type-driven walk missed the SAM form, which is exactly where b2b397a9 was.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "Statement":
                for branch in _branches(value):
                    items = branch if isinstance(branch, list) else [branch]
                    for item in items:
                        for statement in _branches(item):
                            if isinstance(statement, dict):
                                yield statement
            yield from _statements(value)
    elif isinstance(node, list):
        for item in node:
            yield from _statements(item)


def _actions(statement: dict) -> list[str]:
    """Literal action strings in a statement, across ``Fn::If`` branches.

    ``NotAction`` is read too: ``NotAction: ["s3:*"]`` with ``Effect: Allow``
    grants everything else, IAM mutation included.
    """
    found: list[str] = []
    for key in ("Action", "NotAction"):
        for branch in _branches(statement.get(key)):
            items = branch if isinstance(branch, list) else [branch]
            for item in items:
                for leaf in _branches(item):
                    if isinstance(leaf, str):
                        found.append(leaf.strip())
    return found


def _offending_actions(doc: Any) -> list[str]:
    """Permission-mutating actions granted by an ``Allow`` statement in ``doc``."""
    offending = []
    for statement in _statements(doc):
        if str(statement.get("Effect", "Allow")).strip().lower() != "allow":
            continue
        for action in _actions(statement):
            lowered = action.lower()
            # A bare "*" grants every action there is, iam: mutation included.
            if lowered == "*" or lowered in MUTATION_ACTIONS:
                offending.append(action)
    return sorted(set(offending))


def _template_paths(root: Path | None = None) -> list[Path]:
    """Every CloudFormation-looking YAML file in the repo.

    Discovered rather than listed, so a new template is covered the day it is
    added — the failure mode that let the log-group gate miss whole directories
    (see ``test_lambda_log_groups.py``).
    """
    root = root or REPO_ROOT
    paths = []
    for current, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in PRUNED_DIRS]
        for name in files:
            if not (fnmatch.fnmatch(name, "*.yaml") or fnmatch.fnmatch(name, "*.yml")):
                continue
            path = Path(current) / name
            try:
                doc = _load_text(path.read_text())
            except (yaml.YAMLError, UnicodeDecodeError, OSError):
                continue
            if isinstance(doc, dict) and doc.get("Resources"):
                paths.append(path)
    return sorted(paths)


def _scan(root: Path | None = None) -> dict[str, list[str]]:
    """``{relative path: offending actions}`` for every non-exempt template."""
    root = root or REPO_ROOT
    problems: dict[str, list[str]] = {}
    for path in _template_paths(root):
        rel = str(path.relative_to(root))
        if rel in DEPLOYMENT_ROLE_TEMPLATES:
            continue
        try:
            doc = _load_text(path.read_text())
        except (yaml.YAMLError, UnicodeDecodeError, OSError):
            continue
        offending = _offending_actions(doc)
        if offending:
            problems[rel] = offending
    return problems


@pytest.mark.unit
def test_no_template_grants_iam_permission_mutation() -> None:
    """AppSec b2b397a9 as a permanent gate.

    Any principal that can put or attach a policy can grant itself
    ``AdministratorAccess``, which makes every other IAM boundary in the stack
    advisory. If a new grant is genuinely needed, it belongs on a role that
    nothing at runtime can assume — add the template to
    ``DEPLOYMENT_ROLE_TEMPLATES`` with the reason, do not widen a Lambda's
    policy.
    """
    problems = _scan()
    assert not problems, (
        "template(s) grant IAM permission-mutation actions, so the principal "
        "can add permissions to itself (Security Invariant "
        "iam-role-without-privilege-escalation scenario 1.1; AppSec finding "
        f"b2b397a9): {problems}. Remove the action, or — if the role exists in "
        "order to create the stack's roles and no runtime code can assume it — "
        "add the template to DEPLOYMENT_ROLE_TEMPLATES in this file with a "
        "written justification."
    )


@pytest.mark.unit
def test_the_agentcore_gateway_manager_policy_stays_scoped() -> None:
    """b2b397a9's own resource, pinned by name.

    The repo-wide rule above would also catch a regression here, but only while
    the action stays in ``MUTATION_ACTIONS``. This asserts the two properties the
    finding was actually about: the gateway manager grants no ``iam:`` write at
    all, and its ``iam:PassRole`` names one role rather than ``"*"``.
    """
    doc = _load_text((REPO_ROOT / "template.yaml").read_text())
    function = doc["Resources"]["AgentCoreGatewayManagerFunction"]

    iam_statements = []
    for statement in _statements(function):
        actions = [a for a in _actions(statement) if a.lower().startswith("iam:")]
        if actions:
            iam_statements.append((sorted(actions), statement.get("Resource")))

    granted = sorted({action for actions, _ in iam_statements for action in actions})
    assert granted == ["iam:GetRole", "iam:PassRole"], (
        "AgentCoreGatewayManagerFunction's IAM grants changed. It is a "
        "CloudFormation custom resource whose only IAM need is to read and pass "
        "the execution role CloudFormation builds for it; anything more is the "
        f"privilege-escalation path of finding b2b397a9. Got: {granted}"
    )

    for actions, resource in iam_statements:
        assert resource != "*" and resource != ["*"], (
            f"AgentCoreGatewayManagerFunction grants {actions} on Resource '*'. "
            "Scope it to AgentCoreGatewayExecutionRole's ARN."
        )


# Templates that still grant iam:PassRole on Resource "*". Empty by design —
# this is a ratchet, so the list may shrink but never grow. If a legitimate case
# appears, add it here WITH a reason and a follow-up.
PASS_ROLE_WILDCARD_ALLOWED: dict[str, str] = {}


def _wildcard_pass_role(root: Path | None = None) -> dict[str, list[str]]:
    """``{relative path: statements}`` granting ``iam:PassRole`` on ``"*"``."""
    root = root or REPO_ROOT
    problems: dict[str, list[str]] = {}
    for path in _template_paths(root):
        rel = str(path.relative_to(root))
        if rel in DEPLOYMENT_ROLE_TEMPLATES or rel in PASS_ROLE_WILDCARD_ALLOWED:
            continue
        try:
            doc = _load_text(path.read_text())
        except (yaml.YAMLError, UnicodeDecodeError, OSError):
            continue
        for statement in _statements(doc):
            if str(statement.get("Effect", "Allow")).strip().lower() != "allow":
                continue
            if not any(a.lower() == "iam:passrole" for a in _actions(statement)):
                continue
            for branch in _branches(statement.get("Resource")):
                resources = branch if isinstance(branch, list) else [branch]
                if any(r == "*" for r in resources if isinstance(r, str)):
                    problems.setdefault(rel, []).append(str(statement.get("Action")))
    return problems


@pytest.mark.unit
def test_pass_role_is_scoped() -> None:
    """``iam:PassRole`` on ``Resource: "*"`` lets a role hand ANY role to a service.

    That is a privilege-escalation primitive in its own right whenever a
    reachable service will assume the passed role, so it is worth a gate even
    though ``PassRole`` is not itself a permission-mutating action — which is why
    it is not in ``MUTATION_ACTIONS``.
    """
    problems = _wildcard_pass_role()
    assert not problems, (
        "iam:PassRole granted on Resource '*' — the principal can hand ANY role "
        f"in the account to a service that will assume it: {problems}. Scope the "
        "statement to the specific role ARN(s), and add an "
        "iam:PassedToService condition where the service is known."
    )


# ---------------------------------------------------------------------------
# Meta-tests: a gate that cannot fail is worthless. Each case below is a shape
# the rule must catch, including the exact shape b2b397a9 shipped as.
# ---------------------------------------------------------------------------

_SAM_POLICY = """
Resources:
  MyFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
{actions}
              Resource: "*"
"""


@pytest.mark.unit
@pytest.mark.parametrize(
    "case,actions",
    [
        # The finding's own shape: a SAM Policies list, mixed in with the
        # legitimate grants it hid behind.
        (
            "b2b397a9-as-shipped",
            "                - bedrock-agentcore:*\n"
            "                - iam:PassRole\n"
            "                - iam:CreateRole\n"
            "                - iam:AttachRolePolicy\n"
            "                - iam:GetRole\n",
        ),
        ("put-role-policy", "                - iam:PutRolePolicy\n"),
        ("attach-managed-policy", "                - iam:AttachRolePolicy\n"),
        ("create-policy-version", "                - iam:CreatePolicyVersion\n"),
        ("trust-policy", "                - iam:UpdateAssumeRolePolicy\n"),
        ("boundary-removal", "                - iam:DeleteRolePermissionsBoundary\n"),
        ("new-user-credentials", "                - iam:CreateAccessKey\n"),
        ("iam-wildcard", "                - iam:*\n"),
        ("full-wildcard", '                - "*"\n'),
        # Case is not significant in an IAM action.
        ("mixed-case", "                - IAM:putRolePolicy\n"),
    ],
)
def test_gate_catches_privesc_shapes(case: str, actions: str, tmp_path: Path) -> None:
    """Each shape must be reported. Without this the rule can silently weaken."""
    probe = tmp_path / "probe" / "template.yaml"
    probe.parent.mkdir(parents=True)
    probe.write_text(_SAM_POLICY.format(actions=actions))
    assert _scan(root=tmp_path), f"privesc shape {case!r} was NOT caught"


@pytest.mark.unit
def test_gate_catches_a_statement_behind_an_fn_if(tmp_path: Path) -> None:
    """A grant reached through one ``Fn::If`` leg still deploys on that leg."""
    probe = tmp_path / "probe" / "template.yaml"
    probe.parent.mkdir(parents=True)
    probe.write_text(
        "Resources:\n"
        "  MyRole:\n"
        "    Type: AWS::IAM::Role\n"
        "    Properties:\n"
        "      Policies:\n"
        "        - PolicyName: p\n"
        "          PolicyDocument:\n"
        "            Statement: !If\n"
        "              - SomeCondition\n"
        "              - - Effect: Allow\n"
        "                  Action: iam:AttachRolePolicy\n"
        "                  Resource: '*'\n"
        "              - - Effect: Allow\n"
        "                  Action: s3:GetObject\n"
        "                  Resource: '*'\n"
    )
    assert _scan(root=tmp_path), "a grant inside an Fn::If branch was NOT caught"


@pytest.mark.unit
def test_gate_ignores_deny_and_read_only(tmp_path: Path) -> None:
    """The rule must not fire on shapes that grant nothing.

    An explicit ``Deny`` on a mutation action is a *hardening* measure, and
    ``iam:GetRole`` / ``iam:ListRoles`` are reads. A gate that flagged these
    would be turned off.
    """
    probe = tmp_path / "probe" / "template.yaml"
    probe.parent.mkdir(parents=True)
    probe.write_text(
        "Resources:\n"
        "  MyRole:\n"
        "    Type: AWS::IAM::Role\n"
        "    Properties:\n"
        "      Policies:\n"
        "        - PolicyName: p\n"
        "          PolicyDocument:\n"
        "            Statement:\n"
        "              - Effect: Deny\n"
        "                Action: iam:AttachRolePolicy\n"
        "                Resource: '*'\n"
        "              - Effect: Allow\n"
        "                Action:\n"
        "                  - iam:GetRole\n"
        "                  - iam:ListRoles\n"
        "                  - iam:PassRole\n"
        "                Resource: arn:aws:iam::123456789012:role/some-role\n"
    )
    assert not _scan(root=tmp_path), "the gate fired on a Deny or a read-only grant"


@pytest.mark.unit
def test_pass_role_gate_catches_a_wildcard(tmp_path: Path) -> None:
    """The PassRole ratchet must be able to fail.

    Also pins the division of labour between the two rules: a wildcard
    ``PassRole`` is caught by ``_wildcard_pass_role`` and NOT by ``_scan``,
    because ``PassRole`` deliberately is not a mutation action.
    """
    probe = tmp_path / "probe" / "template.yaml"
    probe.parent.mkdir(parents=True)
    probe.write_text(
        "Resources:\n"
        "  MyFn:\n"
        "    Type: AWS::Serverless::Function\n"
        "    Properties:\n"
        "      Policies:\n"
        "        - Statement:\n"
        "            - Effect: Allow\n"
        "              Action: iam:PassRole\n"
        "              Resource: '*'\n"
    )
    assert _wildcard_pass_role(root=tmp_path), "wildcard PassRole was NOT caught"
    assert not _scan(root=tmp_path), (
        "PassRole is not a permission-mutating action and must not be reported by "
        "the mutation rule — otherwise every legitimate custom resource trips it"
    )


@pytest.mark.unit
def test_pass_role_gate_accepts_a_scoped_grant(tmp_path: Path) -> None:
    """A ``PassRole`` naming one role ARN — the shape this PR moved to — passes."""
    probe = tmp_path / "probe" / "template.yaml"
    probe.parent.mkdir(parents=True)
    probe.write_text(
        "Resources:\n"
        "  MyFn:\n"
        "    Type: AWS::Serverless::Function\n"
        "    Properties:\n"
        "      Policies:\n"
        "        - Statement:\n"
        "            - Effect: Allow\n"
        "              Action:\n"
        "                - iam:GetRole\n"
        "                - iam:PassRole\n"
        "              Resource: !GetAtt SomeRole.Arn\n"
    )
    assert not _wildcard_pass_role(root=tmp_path)
    assert not _scan(root=tmp_path)


@pytest.mark.unit
def test_discovery_finds_a_new_template(tmp_path: Path) -> None:
    """The sweep must actually walk the tree.

    Without this, gutting ``_template_paths`` leaves the suite green and the
    coverage guarantee silently gone.
    """
    probe = tmp_path / "some-service" / "template.yml"
    probe.parent.mkdir(parents=True)
    probe.write_text(
        "Resources:\n"
        "  Fn:\n"
        "    Type: AWS::Serverless::Function\n"
        "    Properties:\n"
        "      Handler: index.handler\n"
    )
    assert [p.relative_to(tmp_path) for p in _template_paths(root=tmp_path)] == [
        Path("some-service/template.yml")
    ]


@pytest.mark.unit
def test_exemptions_are_not_stale() -> None:
    """Every allowlisted template must still exist and still need the exemption.

    A stale entry is worse than none: it reads as a reviewed decision while
    silently covering nothing, and it would hide a genuine regression if the
    path were ever reused.
    """
    stale = []
    unnecessary = []
    for rel, reason in DEPLOYMENT_ROLE_TEMPLATES.items():
        path = REPO_ROOT / rel
        if not path.exists():
            stale.append(rel)
            continue
        assert reason.strip(), f"{rel}: exemption has no justification"
        if not _offending_actions(_load_text(path.read_text())):
            unnecessary.append(rel)

    assert not stale, (
        f"DEPLOYMENT_ROLE_TEMPLATES names template(s) that no longer exist: "
        f"{stale}. Remove the stale entries."
    )
    assert not unnecessary, (
        f"DEPLOYMENT_ROLE_TEMPLATES exempts template(s) that no longer grant any "
        f"permission-mutation action: {unnecessary}. Remove the exemption so the "
        f"rule protects them."
    )
