# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""
Default-deny group authorization for the HTTP API dispatcher.

WHY THIS EXISTS
---------------
Under AppSync the schema directive
``@aws_cognito_user_pools(cognito_groups: [...])`` gated a field at the API layer
before any resolver ran, and a field the caller's groups did not satisfy was
rejected there. The REST API that replaced AppSync has one route
(``POST /op/{field}``) behind a Cognito authorizer that **authenticates only** —
it reads no group directives. Authorization therefore became opt-in per resolver:
an operation whose resolver omits its check is reachable by any authenticated
caller (including a caller in no group at all, which self-signup can produce),
and a NEWLY added operation is open unless somebody remembers to add a check.

This module restores the AppSync posture at the API layer. Every request must
name an operation that appears in the bundled manifest AND satisfy that
operation's required groups, or it is denied before dispatch.

**Unmapped means denied.** A field with no manifest entry is rejected — that is
the whole point, not an edge case. A new operation is closed until its required
groups are declared in ``scripts/api_rbac_expectations.yaml`` (which
``scan_api_rbac.py`` already forces for any routable op), rather than open until
someone notices.

RELATIONSHIP TO THE RESOLVER CHECKS
-----------------------------------
This is a floor, not a replacement. The per-resolver group checks (and
``ddb_direct._REQUIRED_GROUPS``) stay exactly as they are: they are the layer
that also enforces per-object scope (config version, test set, ownership), which
a field-level manifest cannot express. Both layers deny with ``PermissionError``,
which the dispatcher maps to HTTP 403 / ``errorType: "Unauthorized"``.

FAIL-CLOSED, UNLIKE ``validation.py``
-------------------------------------
``validation.py`` deliberately fails **open** on its own internal errors: a bug
in an input-shape checker must not 500 the API. This module fails **closed** — a
missing or unreadable manifest denies every request. The two are not
inconsistent: a validator that lets a malformed argument through loses a
defense-in-depth check, while an authorization layer that lets an unknown
operation through loses the guarantee it exists for. The manifest is generated at
build time, committed in this Lambda's CodeUri and drift-guarded in CI
(``generate_api_rbac_manifest.py --check`` plus a unit test), so "manifest
missing" means a broken build, which is a condition to surface loudly rather than
absorb.
"""

import json
import logging
import os
from typing import Any, Dict, List, Union

logger = logging.getLogger()

_MANIFEST_PATH = os.path.join(os.path.dirname(__file__), "api_rbac_manifest.json")

# Manifest schema version this code understands. A manifest from the future is
# treated as unreadable (deny) rather than interpreted optimistically.
_SUPPORTED_VERSION = 1

# Policy sentinels, carried through from scripts/api_rbac_expectations.yaml.
_ANY = "ANY"  # any authenticated Cognito caller
_IAM_ONLY = "IAM_ONLY"  # backend/IAM principals only; no Cognito caller


def _load_manifest() -> Dict[str, Union[str, List[str]]]:
    """Load the bundled required-groups manifest once, at cold start.

    On any failure return an EMPTY map, which denies every operation (see the
    module docstring). The error is logged at ERROR so the cause is one log line
    away rather than inferred from a wall of 403s.
    """
    try:
        with open(_MANIFEST_PATH, "r", encoding="utf-8") as fh:
            manifest = json.load(fh)
        version = manifest.get("version")
        if version != _SUPPORTED_VERSION:
            logger.error(
                "api_rbac_manifest.json version %s is not supported (expected %s); "
                "denying all operations",
                version,
                _SUPPORTED_VERSION,
            )
            return {}
        operations = manifest.get("operations") or {}
        if not isinstance(operations, dict) or not operations:
            logger.error(
                "api_rbac_manifest.json carries no operations; denying all requests"
            )
            return {}
        return operations
    except Exception as e:  # noqa: BLE001
        logger.error(
            "Failed to load api_rbac_manifest.json (%s); denying all operations. "
            "The manifest is generated by scripts/sdlc/generate_api_rbac_manifest.py "
            "and must be bundled in this function's CodeUri.",
            e,
        )
        return {}


REQUIRED_GROUPS: Dict[str, Union[str, List[str]]] = _load_manifest()


def caller_groups(event: Dict[str, Any]) -> List[str]:
    """The caller's Cognito groups, from the VERIFIED token claim only.

    Read from ``identity.claims['cognito:groups']``, which
    ``idp_common.api_adapter.normalize_event`` populates from the API Gateway
    authorizer's JWT claims (and normalizes back to a list). Never from the
    request body or a header, both of which the caller controls.
    """
    identity = event.get("identity") or {}
    claims = identity.get("claims") or {}
    groups = claims.get("cognito:groups") or []
    if isinstance(groups, str):
        groups = [groups]
    return [g for g in groups if isinstance(g, str)]


def enforce(field: str, event: Dict[str, Any]) -> None:
    """Raise ``PermissionError`` unless the caller may invoke ``field``.

    ``PermissionError`` is the dispatcher's existing authorization-denial idiom:
    the handler already maps it to 403 with ``errorType: "Unauthorized"``, which
    is what the UI keys on, so a denial here is indistinguishable to the client
    from a denial raised inside a resolver.
    """
    required = REQUIRED_GROUPS.get(field)

    if required is None:
        # Unmapped: either an unknown field or a routable one whose policy was
        # never declared. Both are denied. The message deliberately does not
        # distinguish the two, so it cannot be used to enumerate operations.
        logger.warning(
            "Denied %s: no required-groups entry in api_rbac_manifest.json "
            "(default deny). Declare the operation's groups in "
            "scripts/api_rbac_expectations.yaml and regenerate the manifest.",
            field,
        )
        raise PermissionError(f"Unauthorized: {field} is not an authorized operation")

    if required == _IAM_ONLY:
        logger.warning("Denied %s: IAM-only operation invoked by a Cognito caller", field)
        raise PermissionError(f"Unauthorized: {field} is not callable via the API")

    if required == _ANY:
        # Any authenticated caller. Authentication itself is established by the
        # route's Cognito authorizer (asserted by check S5 of scan_api_rbac.py),
        # which rejects a missing or invalid token with 401 before this runs.
        return

    groups = caller_groups(event)
    if not set(required).intersection(groups):
        # Log the caller's groups (not the token) so a legitimate denial can be
        # told apart from a misconfigured group mapping.
        logger.warning(
            "Denied %s: caller groups %s do not include any of %s",
            field,
            groups,
            sorted(required),
        )
        raise PermissionError(
            f"Unauthorized: {field} requires one of {sorted(required)}"
        )
